game/urls.py
from django.urls import path
from . import views

app_name = 'game'

urlpatterns = [
    path('', views.game_list, name='game_list'),
    path('rsp/', views.rsp_select, name='rsp_select'),
    path('rsp/<str:pick>', views.rsp_result, name='rsp_result'),
    path('rsp/reset/', views.rsp_reset, name='rsp_reset'),
    path('weapon-create/', views.weapon_create, name='weapon_create'),
    path('weapon-list/', views.weapon_list, name='weapon_list'),
]

jgDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('page/', include('page.urls')),
    path('game/', include('game.urls')),
]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.posting_create, name='posting_create'),
    path('list/', views.posting_list, name='posting_list'),
    path('<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('<int:posting_id>/update/', views.posting_update, name='posting_update'),
    path('<int:posting_id>/delete/', views.posting_delete, name='posting_delete'),
    # [코드 작성] 댓글 삭제 기능을 동작하게 하는 url 작성 (posting_id, comment_id 인자 전달)
    
]

game/models.py
from django.db import models

# Create your models here.
class Weapon(models.Model):
    name = models.CharField(max_length=20)
    power = models.IntegerField()

    def __str__(self):
        return self.name

page/models.py
from django.db import models

# Create your models here.
class Posting(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

# [코드 작성] Comment 모델 작성
# [코드 작성] posting, content, date 필드 생성 (posting은 Posting 모델의 객체를 담고 있음)
# [코드 작성] posting 필드는 ForeignKey를 사용하여 Posting 모델의 객체 담고 있음
# [코드 작성] on_delete=models.CASCADE를 사용하면 posting 객체가 삭제될 경우 posting과 연결되어있는 모든 Comment 객체들을 삭제
# [코드 작성] related_name은 posting 객체와 연결되어있는 Comment 객체를 불러오는 경우에 사용
class Comment(models.Model):
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE, related_name='comment_list')
    content = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.posting.title} - {self.content[:10]}...'

page/forms.py
# [코드 작성] django의 forms 모듈 불러오기
from django import forms
# [코드 작성] models.py의 Posting, Comment 모델 불러오기
from .models import Posting

# [코드 작성] forms의 ModelForm을 상속받는 PostingForm 클래스 생성
# [코드 작성] label은 각각 '제목'과 '내용'으로 설정
# [코드 작성] models의 TextField는 forms의 CharField에 widget을 적용하여 구현
# [코드 작성] Meta 클래스를 정의하여 Posting 모델을 기반으로 하고, 어떤 필드를 form으로 사용할 것인지 지정
class PostingForm(forms.ModelForm):
    title = forms.CharField(label='제목')
    content = forms.CharField(label='내용', widget=forms.Textarea)

    class Meta:
        model = Posting
        fields = ['title', 'content',]

# [코드 작성] forms의 ModelForm을 상속받는 CommentForm 클래스 생성
# [코드 작성] label은 ''로 설정
# [코드 작성] Meta 클래스를 정의하여 Comment 모델을 기반으로 하고, 어떤 필드를 form으로 사용할 것인지 지정

game/views.py
from django.shortcuts import render, redirect
from random import *
from .models import Weapon

# Create your views here.
win = 0
draw = 0
lose = 0

def game_list(request):
    return render(request, 'game/game_list.html')

def rsp_select(request):
    global win, draw, lose
    context = {
        'win': win,
        'draw': draw,
        'lose': lose,
    }
    return render(request, 'game/rsp_select.html', context)

def rsp_result(request, pick):
    global win, draw, lose
    rsp = ['가위', '바위', '보']
    com = choice(rsp)

    if pick == com:
        result = '무승부'
        draw += 1
    elif (pick == '가위' and com == '보') or (pick == '바위' and com == '가위') or (pick == '보' and com == '바위'):
        result = '승리'
        win += 1
    else :
        result = '패배'
        lose += 1

    context = {
        'pick': pick,
        'com': com,
        'result': result,
        'win': win,
        'draw': draw,
        'lose': lose,
    }
    return render(request, 'game/rsp_result.html', context)

def rsp_reset(request):
    global win, draw, lose
    win, draw, lose = 0, 0, 0
    return redirect('game:rsp_select')

def weapon_create(request):
    if request.method == 'POST':
        weapon_name = request.POST.get('weapon-name')
        weapon_power = request.POST.get('weapon-power')
        
        Weapon.objects.create(
            name = weapon_name,
            power = weapon_power,
        )
        return redirect('game:weapon_list')
    else:
        return render(request, 'game/weapon_create.html')

def weapon_list(request):
    weapons = Weapon.objects.all()

    context = {
        'weapons': weapons,
    }
    return render(request, 'game/weapon_list.html', context)

page/views.py
# [코드 추가] get_object_or_404 불러오기
from django.shortcuts import render, redirect, get_object_or_404
# [코드 추가] models.py의 Comment 모델 불러오기
from .models import Posting
# [코드 작성] forms.py의 PostingForm, CommentForm 불러오기
from .forms import PostingForm

# Create your views here.
def index(request):
    return render(request, 'page/index.html')

# [Read] 전체 글 목록 보기
def posting_list(request):
    postings = Posting.objects.all()
    context = {
        'postings': postings,
    }
    return render(request, 'page/posting_list.html', context)

# [Create] 글 작성하기
def posting_create(request):
    if request.method == 'POST':
        # [코드 수정] posting_form에 POST 방식으로 넘어온 PostingForm 저장
        posting_form = PostingForm(request.POST)
        
        # [코드 수정] posting_form이 유효한지 확인하고 저장
        if posting_form.is_valid():
            posting_form.save()
            return redirect('page:posting_list')
    else:
        # [코드 수정] PostingForm을 생성하여 posting_form에 저장
        # [코드 수정] None을 지우고 작성
        posting_form = PostingForm()
    
    context = {
        'posting_type': '글쓰기',
        # [코드 추가] posting_form을 딕셔너리 형식으로 html에 넘겨주기
        'posting_form': posting_form,
    }
    # [코드 수정] 'page/posting_form.html'페이지 렌더링 (context도 같이 전달)
    return render(request, 'page/posting_form.html', context)

# [Read & Create] 작성글 보기 & 댓글 작성
def posting_detail(request, posting_id):
    # [코드 수정] get_object_or_404를 이용하여 존재하지 않는 객체를 불러오려고 하면 에러 페이지를 호출하도록 함
    posting = Posting.objects.get(id=posting_id)
    
    # [코드 작성] request.method가 'POST'일 경우 comment_form에 요청값 저장
    # [코드 작성] comment_form이 유효하면 commit=False를 이용하여 comment에 form 임시저장
    # [코드 작성] comment 객체의 posting 필드에 posting 객체를 저장하고, comment 저장
    # [코드 작성] CommentForm을 생성하여 posting_form에 저장
    # [코드 작성] request.method가 'POST'가 아닐 경우 CommentForm을 생성
    
    
    # [코드 수정] posting_id에 해당하는 posting 객체의 모든 댓글 불러오기
    # [코드 수정] Comment 모델 posting 필드의 related_name 활용
    # [코드 수정] None을 지우고 작성
    comments = None

    context = {
        'posting': posting,
        # [코드 추가] comment_form을 딕셔너리 형식으로 html에 넘겨주기

        # [코드 추가] comments를 딕셔너리 형식으로 html에 넘겨주기

    }
    return render(request, 'page/posting_detail.html', context)

# [Update] 작성글 수정
def posting_update(request, posting_id):
    # [코드 수정] get_object_or_404를 이용하여 존재하지 않는 객체를 불러오려고 하면 에러 페이지를 호출하도록 함
    posting = get_object_or_404(Posting, id=posting_id)

    if request.method == 'POST':
        # [코드 수정] POST 방식으로 넘어온 PostingForm에 posting instance를 담아서 저장
        posting_form = PostingForm(request.POST, instance=posting)

        # [코드 수정] posting_form이 유효한지 확인하고 저장
        if posting_form.is_valid():
            posting_form.save()
            return redirect('page:posting_detail', posting_id)
    else:
        # [코드 수정] PostingForm을 생성하여 posting_form에 저장
        # [코드 수정] None을 지우고 작성
        posting_form = PostingForm(instance=posting)

    context = {
        'posting_type': '글수정',
        'posting': posting,
        # [코드 추가] posting_form을 딕셔너리 형식으로 html에 넘겨주기
        'posting_form': posting_form,
    }
    # [코드 수정] 'page/posting_form.html'페이지 렌더링 (context도 같이 전달)
    return render(request, 'page/posting_form.html', context)

# [Delete] 작성글 삭제
def posting_delete(request, posting_id):
    if request.method == 'POST':
        # [코드 수정] get_object_or_404를 이용하여 존재하지 않는 객체를 불러오려고 하면 에러 페이지를 호출하도록 함
        posting = get_object_or_404(Posting, id=posting_id)
        posting.delete()
        return redirect('page:posting_list')
    return redirect('page:posting_detail', posting_id)

# [Delete] 댓글 삭제
def comment_delete():
    # [코드 작성] request.method가 'POST'일 경우 Comment 모델에서 comment_id에 해당하는 객체 불러오기
    # [코드 작성] comment 삭제하기
    # [코드 추가] posting_id에 해당하는 페이지로 redirect
    return 

game/templates/game/character_list.html
{% extends 'base_dark.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/character_list.css' %}">
{% endblock %}

{% block body %}
  <h1>캐릭터 목록</h1>

  {% for character in characters %}
    <p><li>{{character.name}}</li></p>
  {% empty %}
    <p><li>캐릭터를 선택해주세요.</li></p>
  {% endfor %}
  <hr>

  <form action="" method="post">
    {% csrf_token %}
    <div class="character">
      <input name="character-name" id="character-name" type="text" placeholder="캐릭터 이름을 입력해주세요.">
      <input type="submit" value="캐릭터 생성">
    </div>

  </form>


  
{% endblock %}

game/templates/game/create_weapon.html
{% extends 'base.html' %}

{% block head %}
  <style>
    .weapon {
      padding: 10px;
      margin: 10px;
    }
    input {
      font-family: 'GangwonEdu_OTFBoldA';
    }
    input[type=submit] {
      padding: 5px 10px;
      border: 1px solid;
      border-radius: 10px;
      background-color: Khaki;
      color: SaddleBrown;
      text-decoration: none;
      cursor: pointer;
    }
  </style>
{% endblock %}

{% block body %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="weapon">
      <label for="weapon-name">무기 이름</label>
      <input name="weapon-name" id="weapon-name" type="text">
    </div>

    <div class="weapon">
      <label for="weapon-power">무기 공격력</label>
      <input name="weapon-power" id="weapon-power" type="number">
    </div>

    <div class="weapon">
      <input type="submit" value="무기 생성">
    </div>
  </form>
{% endblock %}

game/templates/game/game_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/game_list.css' %}">
{% endblock %}

{% block body %}
  <h1>게임 목록</h1>

  <!-- [미션] 링크를 눌렀을 때 가위바위보 게임으로 이동하도록 만들기 -->
  <!-- [미션] 링크를 눌렀을 때 무기 목록으로 이동하도록 만들기 -->
  <ol>
    <li><p><a href="{% url 'game:rsp_select'%}">가위바위보 게임</a></p></li>
    <li><p><a href="{% url 'game:weapon_list'%}">무기 목록</a></p></li>
    <li><p><a href="">장고캣의 모험(가제)</a></p></li>
  </ol>
{% endblock %}

game/templates/game/list_weapon.html
{% extends 'base.html' %}

{% block head %}
  <style>
    
  </style>
{% endblock %}

{% block body %}
  <h1>전체 무기 목록</h1>
  <ul>
    {% for weapon in weapons %}
      <!-- [미션] weapon의 power도 화면에 출력되도록 만들기 -->
      <li><p>{{weapon.name}} (공격력: {{weapon.power}})</p></li>
    {% empty %}
      <li><p>무기가 없습니다.</p></li>
    {% endfor %}
  </ul>
{% endblock %}

game/templates/game/result.html
{% extends 'game/rsp.html' %}

{% block rsp %}
  <h1>가위바위보 게임 결과</h1>
  
  <!-- [미션] 가위바위보 중에서 내가 선택한 결과 보여주기 -->
  <p>나는 <b>{{pick}}</b>를 선택했습니다.</p>

  <!-- [미션] 랜덤하게 선택된 컴퓨터의 결과 보여주기 -->
  <p>컴퓨터는 <b>{{com}}</b>를 선택했습니다.</p>

  <h2 style="color: red;">
    {% if result == "승리" %}
      내가 이겼습니다.
    {% elif result == "무승부" %}
      비겼습니다.
    {% else %}
      컴퓨터가 이겼습니다.
    {% endif %}
  </h2>
  
{% endblock %}

game/templates/game/rsp_result.html
{% extends 'game/rsp_select.html' %}
{% load static %}

{% block rsp_head %}
  <link rel="stylesheet" href="{% static 'css/game/rsp_result.css' %}">
{% endblock %}

{% block rsp_body %}
  <h1>가위바위보 게임 결과</h1>
  
  <p>나는 <b>{{pick}}</b>를 선택했습니다.</p>
  <p>컴퓨터는 <b>{{com}}</b>를 선택했습니다.</p>

  <h2 class="rsp__result">
    {% if result == "승리" %}
      내가 이겼습니다.
    {% elif result == "무승부" %}
      비겼습니다.
    {% else %}
      컴퓨터가 이겼습니다.
    {% endif %}
  </h2>
  
{% endblock %}

game/templates/game/rsp_select.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/rsp_select.css' %}">
  {% block rsp_head %}
  {% endblock %}
{% endblock %}

{% block body %}

  {% block rsp_body %}
    <h1>가위바위보 게임</h1>

  {% endblock %}
  <div class="rsp__count">
    <p>승리 횟수 : {{win}}회</p>
    <p>무승부 횟수 : {{draw}}회</p>
    <p>패배 횟수 : {{lose}}회</p>

    <a href="{% url 'game:rsp_reset' %}">초기화</a>
  </div>

  <h3>선택해주세요~</h3>
  <div class="rsp__button">
    <a href="{% url 'game:rsp_result' '가위' %}">가위</a>
    <a href="{% url 'game:rsp_result' '바위' %}">바위</a>
    <a href="{% url 'game:rsp_result' '보' %}">보</a>
  </div>
  
{% endblock %}

game/templates/game/weapon_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/weapon_create.css' %}">
{% endblock %}

{% block body %}
  <h1>무기 생성</h1>
  
  <form action="" method="post">
    {% csrf_token %}
    <div class="weapon">
      <label for="weapon-name">무기 이름</label>
      <input name="weapon-name" id="weapon-name" type="text">
    </div>

    <div class="weapon">
      <label for="weapon-power">무기 공격력</label>
      <input name="weapon-power" id="weapon-power" type="number">
    </div>

    <div class="weapon">
      <input type="submit" value="무기 생성">
    </div>
  </form>
{% endblock %}

game/templates/game/weapon_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/game/weapon_list.css' %}">
{% endblock %}

{% block body %}
  <h1>전체 무기 목록</h1>

  <ul>
    {% for weapon in weapons %}
      <li><p>{{weapon.name}} (공격력: {{weapon.power}})</p></li>
    {% empty %}
      <li><p>무기가 없습니다.</p></li>
    {% endfor %}
    <!-- [미션] 링크를 눌렀을 때 무기 생성 페이지로 이동하도록 만들기 -->
    <a class="button" href="{% url 'game:weapon_create' %}">무기 생성하기</a>
  </ul>
{% endblock %}

jgDjango/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>jgDjango</title>
  <link rel="icon" href="{% static 'images/favicon-96x96.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="navbar">
    <span>
      <a href="{% url 'page:index' %}">
        <img class="logo" src="{% static 'images/jgcat.jpg' %}" alt="jgcat">
      </a>
    </span>
    <span>
      <a href="{% url 'page:posting_list' %}">글목록</a>
    </span>
    <span>
      <a href="{% url 'page:posting_create' %}">글쓰기</a>
    </span>
    <!-- [미션] 상단의 네비게이션 바를 통해 '게임목록'에 들어갈 수 있도록 코드 작성하기 -->
    <span>
      <a href="{% url 'game:game_list' %}">게임목록</a>
    </span>
  </div>

  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
</body>
</html>

page/templates/page/create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/create.css' %}">
{% endblock %}

{% block body %}
  <h1>글쓰기</h1>
  
  <!-- [미션] form의 전달방식을 post로 설정하기 -->
  <form action="" method="post">
    <!-- [미션] csrf_token 설정하기 -->
    {% csrf_token %}
    <table>
      <tr>
        <td><label for="title">제목</label></td>
        <!-- [미션] 서버에 딕셔너리 형식으로 전달되는 값의 Key값을 'title'로 설정하기 -->
        <td><input class="title" name="title" id="title" type="text" maxlength=50></td>
      </tr>
    </table>
    
    <br>

    <table>
      <tr>
        <td colspan="2">
          <label for="content">내용</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <!-- [미션] 서버에 딕셔너리 형식으로 전달되는 값의 Key값을 'content'로 설정하기 -->
          <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </td>
      </tr>
    </table>

    <div class="right">
      <input class="button" type="submit" value="등록">
    </div>
  </form>
{% endblock %}

page/templates/page/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/index.css' %}">
{% endblock %}

{% block body %}
  <h1>메인 페이지</h1>
  
  <p>오늘의 목표</p>
  <ol>
    <li>Django에서 Form을 활용하는 방법에 대해 알아봅시다.</li>
    <li>관계형 데이터베이스를 생성해봅시다.</li>
    <li>댓글 기능을 구현해봅시다.</li>
  </ol>

  <img src="{% static 'images/walnut.jpg' %}" alt="walnut">
{% endblock %}

page/templates/page/posting_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_create.css' %}">
{% endblock %}

{% block body %}
  <h1>글쓰기</h1>
  
  <form action="" method="post">
    {% csrf_token %}
    <table>
      <tr>
        <td><label for="title">제목</label></td>
        <td><input class="title" name="title" id="title" type="text" maxlength=50></td>
      </tr>
    </table>
    
    <br>

    <table>
      <tr>
        <td colspan="2">
          <label for="content">내용</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <textarea name="content" id="content" cols="30" rows="10"></textarea>
        </td>
      </tr>
    </table>

    <div class="right">
      <input class="button" type="submit" value="등록">
    </div>
  </form>
{% endblock %}

page/templates/page/posting_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_detail.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 보기</h1>

  <div class="posting">
    <table class="posting__detail">
      <tr>
        <td class="posting__detail__title">{{posting.title}}</td>
        <td class="posting__detail__function">
          <div>
            <a class="button" href="{% url 'page:posting_update' posting.id %}">수정</a>
            <!-- [코드 추가] POST 방식으로 작성글 삭제 후 action을 이용해 해당 url로 이동 -->
            <form action="{% url 'page:posting_delete' posting.id %}" method="post">
              {% csrf_token %}
              <input class="button" type="submit" value="삭제">
            </form>
          </div>
        </td>
      </tr>
      <tr>
        <td class="posting__detail__date" colspan="2">작성일 : {{posting.date|date:'Y-m-d A f'}}</td>
      </tr>
      <tr>
        <td class="posting__detail__content" colspan="2">
          <div class="content">
            {{posting.content}}
          </div>
        </td>
      </tr>
      <tr>
        <td class="posting__detail__function transparent" colspan="2">
          <div>
            <a class="button" href="{% url 'page:posting_list' %}">글 목록</a>
          </div>
        </td>
      </tr>
    </table>

    <table class="posting__comment">
      <tr>
        <th colspan="2">댓글</th>
      </tr>
      <tr>
        <td class="posting__comment__create" colspan="2">
          <!-- POST 방식으로 댓글 작성 -->
          <form action="" method="post">
            {% csrf_token %}
            <div>
              <!-- [코드 작성] Django에서 생성된 comment_form을 div태그 안쪽에 배치 -->
              
              <input class="button" type="submit" value="작성">
            </div>
          </form>
        </td>
      </tr>
      <!-- 반복문을 이용하여 전체 댓글 보여주기 -->
      {% for comment in comments %}
        <tr>
          <td class="posting__comment__content">
            <!-- 댓글 내용 -->
            {{comment.content}}
          </td>
          <td class="posting__comment__delete" rowspan="2">
            <!-- [코드 추가] POST 방식으로 댓글 삭제 후 action을 이용해 해당 url로 이동 -->
            <form action="" method="post">
              {% csrf_token %}
              <input type="submit" value="x">
            </form>
          </td>
        </tr>
        <tr>
          <td class="posting__comment__date">
            <!-- 댓글 작성 시간 -->
            {{comment.date|date:'Y-m-d A f'}}
          </td>
        </tr>
        <tr>
          <td colspan="2">
            <!-- 댓글 구분 선 -->
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% empty %}
        <tr>
          <td class="posting__comment__content" colspan="2">
            댓글이 아직 작성되지 않았습니다.
          </td>
        </tr>
        <tr>
          <td class="posting__comment__date"></td>
        </tr>
        <tr>
          <td colspan="2">
            <hr class="posting__comment__line">
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

page/templates/page/posting_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_form.css' %}">
{% endblock %}

{% block body %}
  <h1>{{posting_type}}</h1>

  <div class="posting-form">
    <form action="" method="post">
      {% csrf_token %}
      <!-- [코드 작성] Django에서 생성된 posting_form을 p태그 안쪽에 배치  -->
      {{posting_form.as_p}}
  
      <div class="posting-form__function--bottom">
        <!-- 글을 수정하기 위해 posting 객체가 같이 전달된 경우에는 취소 버튼 보여주기 -->
        {% if posting %}
          <a class="button" href="{% url 'page:posting_detail' posting.id %}">취소</a>
        {% endif %}
        <input class="button" type="submit" value="등록">
      </div>
    </form>
  </div>
{% endblock %}

page/templates/page/posting_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_list.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 목록</h1>

  <div class="posting">
    <div class="posting__function--top">
      <a class="button" href="{% url 'page:posting_create' %}">글쓰기</a>
    </div>
  
    <table class="posting__list">
      <tr>
        <th class="index">번호</th>
        <th class="title">제목</th>
        <th class="date">날짜</th>
      </tr>
      {% for posting in postings reversed %}
        <tr>
          <td class="index">{{forloop.revcounter}}</td>
          <td class="title"><a href="{% url 'page:posting_detail' posting.id %}">{{posting.title}}</a></td>
          <td class="date">{{posting.date|date:'Y-m-d'}}</td>
        </tr>
      {% empty %}
        <tr>
          <td class="index">-</td>
          <td class="title">글을 작성해주세요.</td>
          <td class="date">-</td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

page/templates/page/posting_update.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/posting_update.css' %}">
{% endblock %}

{% block body %}
  <h1>글수정</h1>

  <form action="" method="post">
    {% csrf_token %}
    <table>
      <tr>
        <td><label for="title">제목</label></td>
        <td><input class="title" name="title" id="title" type="text" maxlength=50 value="{{posting.title}}"></td>
      </tr>
    </table>
    
    <br>

    <table>
      <tr>
        <td colspan="2">
          <label for="content">내용</label>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <textarea name="content" id="content" cols="30" rows="10">{{posting.content}}</textarea>
        </td>
      </tr>
    </table>

    <div class="right">
      <input class="button" type="submit" value="등록">
    </div>
  </form>
{% endblock %}

page/templates/page/read.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/page/read.css' %}">
{% endblock %}

{% block body %}
  <h1>작성 글 목록</h1>

  <div class="right">
    <a class="button" href="{% url 'page:create' %}">글쓰기</a>
  </div>

  <table>
    <tr>
      <th class="index">번호</th>
      <th class="title">제목</th>
      <th class="date">날짜</th>
    </tr>
    <!-- [미션] reversed를 이용해 for문을 거꾸로 반복하기 -->
    {% for posting in postings reversed %}
      <tr>
        <!-- [미션] forloop.revcounter를 이용하여 반복문의 index를 거꾸로 보여주기 -->
        <td class="index">{{forloop.revcounter}}</td>
        <td class="title"><a href="{% url 'page:detail' posting.id %}">{{posting.title}}</a></td>
        <!-- 날짜를 보여주는 형식을 'Y-m-d'로 지정하기 -->
        <td class="date">{{posting.date|date:'Y-m-d'}}</td>
      </tr>
    <!-- for문의 리스트가 비어있을 경우에 보여주는 내용 -->
    {% empty %}
      <tr>
        <td class="index">-</td>
        <td class="title">글을 작성해주세요.</td>
        <td class="date">-</td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}